# Generated by Django 5.0.4 on 2024-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
