# Generated by Django 5.0.4 on 2024-05-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Enter the name of the book')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='Name of author')),
                ('publication_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('genre', models.CharField(max_length=100, null=True, verbose_name='Enter the genre of the book')),
                ('language', models.CharField(max_length=100, null=True, verbose_name='Enter the language of the book')),
                ('num_pages', models.IntegerField(null=True)),
                ('video', models.URLField(blank=True, null=True, verbose_name='Send a link')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Write some information')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Upload a picture please')),
                ('music', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Upload a music file')),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'List of books',
            },
        ),
        migrations.DeleteModel(
            name='PostNews',
        ),
    ]
