# Generated by Django 5.0.4 on 2024-06-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephone", "0004_remove_comment_created_at_alter_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="description",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Write some information"
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                verbose_name="Upload a picture please",
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="in_stock",
            field=models.BooleanField(default=True, null=True, verbose_name="In Stock"),
        ),
    ]
