# Generated by Django 5.0.4 on 2024-05-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephone', '0004_comment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='phone',
        ),
    ]
