# Generated by Django 5.0.4 on 2024-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephone", "0005_phone_description_phone_image_phone_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Upload a picture please"
            ),
        ),
    ]
