# Generated by Django 5.0.4 on 2024-06-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephone", "0006_alter_phone_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="second_model",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Upload a second model"
            ),
        ),
        migrations.AddField(
            model_name="phone",
            name="third_model",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Upload a third model"
            ),
        ),
    ]
