# Generated by Django 5.0.4 on 2024-05-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephone', '0006_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
