# Generated by Django 5.0.4 on 2024-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telephone", "0007_phone_second_model_phone_third_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phone",
            name="price",
        ),
        migrations.AddField(
            model_name="phone",
            name="price_for_first",
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="price_for_second",
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="price_for_third",
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name="phone",
            name="sale",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Is has a sale?"
            ),
        ),
    ]
