# Generated by Django 5.0.4 on 2024-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainGadgets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gadget_image",
                    models.ImageField(
                        upload_to="images/", verbose_name="Upload a picture please"
                    ),
                ),
                ("gadget_title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Gadgets",
                "verbose_name_plural": "List of gadgets",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_title", models.CharField(max_length=100)),
                ("sale_advantage", models.CharField(max_length=100)),
                ("sale_price", models.PositiveIntegerField(default=1000)),
                (
                    "sale_image",
                    models.ImageField(
                        upload_to="images/", verbose_name="Upload a picture please"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales",
                "verbose_name_plural": "List of sales",
            },
        ),
    ]
